In [12]:
import pandas as pd
from great_tables import GT, html, style, loc, google_font
from great_tables.data import sp500

In [ ]:
caltrain_df = pd.read_csv("../../example_datasets/caltrain_weekend_northbound.csv")
caltrain_df.insert(0, 'fare_zone', [4]*4 + [3]*6 + [2]*10 + [1]*4)
caltrain_df.head(5)

,fare_zone,Stop,601,603,605,607,609,611,613,615,...,647,649,651,653,655,657,659,661,663,665
0,4,Tamien,6:51a,NaN,7:51a,NaN,8:51a,NaN,9:51a,NaN,...,NaN,6:51p,NaN,7:51p,NaN,8:51p,NaN,9:51p,NaN,11:25p
1,4,San Jose Diridon,6:56a,7:26a,7:56a,8:26a,8:56a,9:26a,9:56a,10:26a,...,6:26p,6:56p,7:26p,7:56p,8:26p,8:56p,9:26p,9:56p,10:30p,11:30p
2,4,Santa Clara,7:02a,7:32a,8:02a,8:32a,9:02a,9:32a,10:02a,10:32a,...,6:32p,7:02p,7:32p,8:02p,8:32p,9:02p,9:32p,10:02p,10:36p,11:36p
3,4,Lawrence,7:07a,7:37a,8:07a,8:37a,9:07a,9:37a,10:07a,10:37a,...,6:37p,7:07p,7:37p,8:07p,8:37p,9:07p,9:37p,10:07p,10:41p,11:41p
4,3,Sunnyvale,7:11a,7:41a,8:11a,8:41a,9:11a,9:41a,10:11a,10:41a,...,6:41p,7:11p,7:41p,8:11p,8:41p,9:11p,9:41p,10:11p,10:45p,11:45p

In [223]:
train_columns=caltrain_df.filter(regex=("^6")).columns.tolist()
caltrain_table = (
    GT(caltrain_df)
    .tab_header(
        title=html(
            """
                <span style="color: rgb(224,37,33); font-weight: bold; font-size: 40px;">Northbound &ndash;</span>
                <span style="color: black; font-weight: bold; font-size: 30px">
                    WEEKEND SERVICE to SAN FRANCISCO
                </span>
            """
        )
    )
    .tab_stub('fare_zone')
    .tab_source_note(
        source_note=
        """
            Sourced from CalTrain's 01/31/26 weekend schedule. 
        """
    )
    .cols_width(
        cases={
            'Stop':'300px'
        }
    )
    .opt_align_table_header(align='left')
    .cols_align(align='center')
    .tab_style(
        locations=loc.header(),
        style=style.css(
            "color: rgb(224,37,33) !important; font-size: 35px !important; font-weight: bold !important; border-width: 0px !important;",
        )
    )
    .tab_style(
        locations=loc.column_labels(),
        style=style.css(
            "background-color: black !important; color: white !important; font-size: 16px !important; font-weight: bold !important; border-left: grey 4px !important; border-width: 4px !important; border-right: grey 4px !important;"
        )
    )
    .tab_style(
        locations=loc.stub(),
        style=style.css(
            "background-color: rgb(224,37,33) !important; color: white !important; writing-mode: sideways-lr; font-size: 14px !important; font-weight: normal !important; align: left !important"
        )
    )
    .tab_style(
        locations=loc.body(),
        style=style.css(
            """
            height: 10px !important; 
            border-left: solid #a2a7a8 1px !important;
            border-right: solid #a2a7a8 1px !important;
            color: black !important
            """
        )
    )
    .tab_options(
        row_group_as_column=True,
        row_striping_background_color="#e1e2e2"
    )
    .cols_label(
        Stop='Train No.',
        fare_zone='Fare Zone'
    )
    .opt_row_striping()
    .opt_table_outline()
    .opt_table_font(font=google_font('frutiger'))
)
caltrain_table

GT(_tbl_data=    fare_zone              Stop    601    603    605    607     609     611  \
0           4            Tamien  6:51a    NaN  7:51a    NaN   8:51a     NaN
1           4  San Jose Diridon  6:56a  7:26a  7:56a  8:26a   8:56a   9:26a
2           4       Santa Clara  7:02a  7:32a  8:02a  8:32a   9:02a   9:32a
3           4          Lawrence  7:07a  7:37a  8:07a  8:37a   9:07a   9:37a
4           3         Sunnyvale  7:11a  7:41a  8:11a  8:41a   9:11a   9:41a
5           3     Mountain View  7:15a  7:45a  8:15a  8:45a   9:15a   9:45a
6           3       San Antonio  7:18a  7:48a  8:18a  8:48a   9:18a   9:48a
7           3    California Ave  7:21a  7:51a  8:21a  8:51a   9:21a   9:51a
8           3         Palo Alto  7:24a  7:54a  8:24a  8:54a   9:24a   9:54a
9           3        Menlo Park  7:26a  7:56a  8:26a  8:56a   9:26a   9:56a
10          2      Redwood City  7:32a  8:02a  8:32a  9:02a   9:32a  10:02a
11          2        San Carlos  7:35a  8:05a  8:35a  9:05a   9:35a  10:05a
12          2           Belmont  7:38a  8:08a  8:38a  9:08a   9:38a  10:08a
13          2         Hillsdale  7:41a  8:11a  8:41a  9:11a   9:41a  10:11a
14          2      Hayward Park  7:43a  8:13a  8:43a  9:13a   9:43a  10:13a
15          2         San Mateo  7:46a  8:16a  8:46a  9:16a   9:46a  10:16a
16          2        Burlingame  7:48a  8:18a  8:48a  9:18a   9:48a  10:18a
17          2          Broadway  7:51a  8:21a  8:51a  9:21a   9:51a  10:21a
18          2          Millbrae  7:54a  8:24a  8:54a  9:24a   9:54a  10:24a
19          2         San Bruno  7:57a  8:27a  8:57a  9:27a   9:57a  10:27a
20          1  S. San Francisco  8:00a  8:30a  9:00a  9:30a  10:00a  10:30a
21          1          Bayshore  8:05a  8:35a  9:05a  9:35a  10:05a  10:35a
22          1       22nd Street  8:10a  8:40a  9:10a  9:40a  10:10a  10:40a
23          1     San Francisco  8:16a  8:46a  9:16a  9:46a  10:16a  10:46a

       613     615  ...    647    649    651    653    655     657     659  \
0    9:51a     NaN  ...    NaN  6:51p    NaN  7:51p    NaN   8:51p     NaN
1    9:56a  10:26a  ...  6:26p  6:56p  7:26p  7:56p  8:26p   8:56p   9:26p
2   10:02a  10:32a  ...  6:32p  7:02p  7:32p  8:02p  8:32p   9:02p   9:32p
3   10:07a  10:37a  ...  6:37p  7:07p  7:37p  8:07p  8:37p   9:07p   9:37p
4   10:11a  10:41a  ...  6:41p  7:11p  7:41p  8:11p  8:41p   9:11p   9:41p
5   10:15a  10:45a  ...  6:45p  7:15p  7:45p  8:15p  8:45p   9:15p   9:45p
6   10:18a  10:48a  ...  6:48p  7:18p  7:48p  8:18p  8:48p   9:18p   9:48p
7   10:21a  10:51a  ...  6:51p  7:21p  7:51p  8:21p  8:51p   9:21p   9:51p
8   10:24a  10:54a  ...  6:54p  7:24p  7:54p  8:24p  8:54p   9:24p   9:54p
9   10:26a  10:56a  ...  6:56p  7:26p  7:56p  8:26p  8:56p   9:26p   9:56p
10  10:32a  11:02a  ...  7:02p  7:32p  8:02p  8:32p  9:02p   9:32p  10:02p
11  10:35a  11:05a  ...  7:05p  7:35p  8:05p  8:35p  9:05p   9:35p  10:05p
12  10:38a  11:08a  ...  7:08p  7:38p  8:08p  8:38p  9:08p   9:38p  10:08p
13  10:41a  11:11a  ...  7:11p  7:41p  8:11p  8:41p  9:11p   9:41p  10:11p
14  10:43a  11:13a  ...  7:13p  7:43p  8:13p  8:43p  9:13p   9:43p  10:13p
15  10:46a  11:16a  ...  7:16p  7:46p  8:16p  8:46p  9:16p   9:46p  10:16p
16  10:48a  11:18a  ...  7:18p  7:48p  8:18p  8:48p  9:18p   9:48p  10:18p
17  10:51a  11:21a  ...  7:21p  7:51p  8:21p  8:51p  9:21p   9:51p  10:21p
18  10:54a  11:24a  ...  7:24p  7:54p  8:24p  8:54p  9:24p   9:54p  10:24p
19  10:57a  11:27a  ...  7:27p  7:57p  8:27p  8:57p  9:27p   9:57p  10:27p
20  11:00a  11:30a  ...  7:30p  8:00p  8:30p  9:00p  9:30p  10:00p  10:30p
21  11:05a  11:35a  ...  7:35p  8:05p  8:35p  9:05p  9:35p  10:05p  10:35p
22  11:10a  11:40a  ...  7:40p  8:10p  8:40p  9:10p  9:40p  10:10p  10:40p
23  11:16a  11:46a  ...  7:46p  8:16p  8:46p  9:16p  9:46p  10:16p  10:46p

       661     663     665
0    9:51p     NaN  11:25p
1    9:56p  10:30p  11:30p
2   10:02p  10:36p  11:36p
3   10:07p  10:41p  11:41p
4   10:11p  10:45p  11:45p
5   10:15p  10:49p  11:49p
6   10:18p  10:52p  11:52p
7   10:21p  10:55p  11:55p
8   10:24p  10:58p  11:58p
9   10:26p  11:00p  12:00a
10  10:32p  11:06p  12:06a
11  10:35p  11:09p  12:09a
12  10:38p  11:12p  12:12a
13  10:41p  11:15p  12:15a
14  10:43p  11:17p  12:17a
15  10:46p  11:20p  12:20a
16  10:48p  11:22p  12:22a
17  10:51p  11:25p  12:25a
18  10:54p  11:28p  12:28a
19  10:57p  11:31p  12:31a
20  11:00p  11:34p  12:34a
21  11:05p  11:39p  12:39a
22  11:10p  11:44p  12:44a
23  11:16p  11:50p  12:50a


In [ ]:

train_columns.head(10)

,601,603,605,607,609,611,613,615,617,619,...,647,649,651,653,655,657,659,661,663,665
0,6:51a,NaN,7:51a,NaN,8:51a,NaN,9:51a,NaN,10:51a,NaN,...,NaN,6:51p,NaN,7:51p,NaN,8:51p,NaN,9:51p,NaN,11:25p
1,6:56a,7:26a,7:56a,8:26a,8:56a,9:26a,9:56a,10:26a,10:56a,11:26a,...,6:26p,6:56p,7:26p,7:56p,8:26p,8:56p,9:26p,9:56p,10:30p,11:30p
2,7:02a,7:32a,8:02a,8:32a,9:02a,9:32a,10:02a,10:32a,11:02a,11:32a,...,6:32p,7:02p,7:32p,8:02p,8:32p,9:02p,9:32p,10:02p,10:36p,11:36p
3,7:07a,7:37a,8:07a,8:37a,9:07a,9:37a,10:07a,10:37a,11:07a,11:37a,...,6:37p,7:07p,7:37p,8:07p,8:37p,9:07p,9:37p,10:07p,10:41p,11:41p
4,7:11a,7:41a,8:11a,8:41a,9:11a,9:41a,10:11a,10:41a,11:11a,11:41a,...,6:41p,7:11p,7:41p,8:11p,8:41p,9:11p,9:41p,10:11p,10:45p,11:45p
5,7:15a,7:45a,8:15a,8:45a,9:15a,9:45a,10:15a,10:45a,11:15a,11:45a,...,6:45p,7:15p,7:45p,8:15p,8:45p,9:15p,9:45p,10:15p,10:49p,11:49p
6,7:18a,7:48a,8:18a,8:48a,9:18a,9:48a,10:18a,10:48a,11:18a,11:48a,...,6:48p,7:18p,7:48p,8:18p,8:48p,9:18p,9:48p,10:18p,10:52p,11:52p
7,7:21a,7:51a,8:21a,8:51a,9:21a,9:51a,10:21a,10:51a,11:21a,11:51a,...,6:51p,7:21p,7:51p,8:21p,8:51p,9:21p,9:51p,10:21p,10:55p,11:55p
8,7:24a,7:54a,8:24a,8:54a,9:24a,9:54a,10:24a,10:54a,11:24a,11:54a,...,6:54p,7:24p,7:54p,8:24p,8:54p,9:24p,9:54p,10:24p,10:58p,11:58p
9,7:26a,7:56a,8:26a,8:56a,9:26a,9:56a,10:26a,10:56a,11:26a,11:56a,...,6:56p,7:26p,7:56p,8:26p,8:56p,9:26p,9:56p,10:26p,11:00p,12:00a